<?php
require_once __DIR__ . '/../includes/auth.php';
require_login();

require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../includes/functions.php';

$summary = $conn->query("CALL sp_department_summary()");

include __DIR__ . '/../includes/header.php';
include __DIR__ . '/../includes/navbar.php';
?>

<?php show_flash(); ?>

<div class="page-header">
    <div>
        <div class="page-kicker">Reports / Stored Procedure</div>
        <h1 class="page-title">Department Summary Report</h1>
        <p class="page-subtitle">
            This report is generated by calling the MySQL stored procedure 
            <strong>sp_department_summary()</strong>.
        </p>
    </div>

    <div class="d-flex gap-2 flex-wrap">
        <a href="/employee-management-system/reports/department_report.php" class="btn btn-outline-primary">
            <i class="bi bi-diagram-3 me-1"></i> JOIN Report
        </a>

        <a href="/employee-management-system/dashboard.php" class="btn btn-outline-secondary">
            <i class="bi bi-arrow-left me-1"></i> Dashboard
        </a>
    </div>
</div>

<div class="row g-3 mb-4">
    <div class="col-lg-4 col-md-6">
        <div class="card-modern stat-card">
            <div class="stat-icon">
                <i class="bi bi-database-check"></i>
            </div>
            <div class="stat-label">Database Feature</div>
            <div class="stat-value" style="font-size: 24px;">Procedure</div>
            <div class="stat-note">CALL sp_department_summary()</div>
        </div>
    </div>

    <div class="col-lg-4 col-md-6">
        <div class="card-modern stat-card">
            <div class="stat-icon">
                <i class="bi bi-diagram-3"></i>
            </div>
            <div class="stat-label">Report Scope</div>
            <div class="stat-value" style="font-size: 24px;">Departments</div>
            <div class="stat-note">Department-based analysis</div>
        </div>
    </div>

    <div class="col-lg-4 col-md-6">
        <div class="card-modern stat-card">
            <div class="stat-icon">
                <i class="bi bi-cash-stack"></i>
            </div>
            <div class="stat-label">Calculated Field</div>
            <div class="stat-value" style="font-size: 24px;">AVG Salary</div>
            <div class="stat-note">Computed inside MySQL</div>
        </div>
    </div>
</div>

<div class="card-modern">
    <div class="p-4 border-bottom d-flex flex-wrap justify-content-between align-items-center gap-3">
        <div>
            <h5 class="fw-bold mb-1">Stored Procedure Result</h5>
            <div class="text-muted small">
                Data below is returned directly from the MySQL stored procedure.
            </div>
        </div>

        <span class="badge rounded-pill text-bg-success">
            Stored Procedure Active
        </span>
    </div>

    <div class="table-responsive">
        <table class="table table-modern">
            <thead>
                <tr>
                    <th>Department</th>
                    <th>Total Employees</th>
                    <th>Active</th>
                    <th>Inactive</th>
                    <th>Average Salary</th>
                </tr>
            </thead>

            <tbody>
                <?php if (!$summary || $summary->num_rows === 0): ?>
                    <tr>
                        <td colspan="5" class="text-center text-muted py-5">
                            <i class="bi bi-database-x d-block fs-2 mb-2"></i>
                            No department summary data found.
                        </td>
                    </tr>
                <?php endif; ?>

                <?php if ($summary): ?>
                    <?php while ($row = $summary->fetch_assoc()): ?>
                        <tr>
                            <td>
                                <div class="employee-name">
                                    <div class="employee-avatar">
                                        <?php echo e(strtoupper(substr($row['department_name'], 0, 2))); ?>
                                    </div>

                                    <div>
                                        <strong><?php echo e($row['department_name']); ?></strong>
                                        <small>Department ID: <?php echo e($row['department_id']); ?></small>
                                    </div>
                                </div>
                            </td>

                            <td>
                                <span class="fw-bold">
                                    <?php echo e($row['total_employees']); ?>
                                </span>
                            </td>

                            <td>
                                <span class="status-pill status-active">
                                    <?php echo e($row['active_employees']); ?> Active
                                </span>
                            </td>

                            <td>
                                <span class="status-pill status-inactive">
                                    <?php echo e($row['inactive_employees']); ?> Inactive
                                </span>
                            </td>

                            <td>
                                <?php echo e(number_format((float)$row['average_salary'], 2)); ?> ₺
                            </td>
                        </tr>
                    <?php endwhile; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<div class="card-modern p-4 mt-4">
    <h5 class="fw-bold mb-2">How this report works</h5>
    <p class="text-muted mb-0">
        The PHP page calls the stored procedure using MySQLi with 
        <code>CALL sp_department_summary()</code>. The procedure performs a 
        LEFT JOIN between departments and employees, groups the result by department, 
        and calculates total employees, active employees, inactive employees, and average salary.
    </p>
</div>

<?php
if ($summary) {
    $summary->free();
}

while ($conn->more_results() && $conn->next_result()) {
    $extraResult = $conn->store_result();
    if ($extraResult) {
        $extraResult->free();
    }
}

include __DIR__ . '/../includes/footer.php';
?>